config/routes.rb
Rails.application.routes.draw do
    root "artists#index"

    resources :artists, only: [:index, :show, :destroy] do
      resources :songs, only: [:new, :create, :destroy]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name, presence: true
  validates :photo, presence: true

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:index, :show,:destroy]

  def index
    @artists = Artist.all
  end

  def show
    @songs = @artist.songs.all
    @song = Song.new
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
      redirect_to artists_url, notice: 'Artist deleted.'
  end

  private
    def set_artist
      @artist = Artist.find_by_id(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :image, :songs_id)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
      before_action :set_artist
      before_action :set_song

  def new
    @song = Song.new
  end

  def create
  @artist = Artist.find(params[:artist_id])
  @song = @artist.songs.new(song_params)
  @song.artist_id = params[:artist_id]

  respond_to do |format|
    if @song.save
      format.html { redirect_to @song.artist, notice: "Song has been created" }
      format.json { render :show, status: :created, location: @song }
    else
      format.html { render :new }
      format.json { render json: @song.errors, status: :unprocessable_entity }
    end
  end
end

  def destroy
    @song.destroy
    respond_to do |format|
    format.html { redirect_to @song.artist, notice: "Song deleted" }
    format.json { head :no_content }
  end
end

  private

    def set_song
    @song = Song.find_by_id(params[:id])
    end

    def song_params
    params.require(:song).permit(:title, :artist_id)
    end

    def set_artist
    @artist = Artist.find_by_id(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h3><bold>Artists at:<bold><h3>
<h2><strong> Codaisseurify <strong> <h2>

    <% @artists.each do |artist| %>
    <div class="row">
      <div class="col-md-7">
        <h4><%=link_to artist.name, artist%></h4>
        <div class="img">
          <%= image_tag artist.photo %>
        </div>
      </div>
    </div>
    <% end %>


    <style>
    img {
        display: inline-block;
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px;
        width: 300px;
    }

    img:hover {
        box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
    }
    </style>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1><strong>Artist</strong></h1>
    <%= @artist.name %>
    <div class="img">
      <%= image_tag @artist.photo %>
    </div>
    <div class="allsongs">
       <% if @songs!= nil %>
    <%@artist.songs.each do |song|%>
  <ul id="songlist">
    <li class="song">
    <input id="song1" type="checkbox">
    <label for="song1"><%=song.title%></li>
    <h6><%=link_to "Delete song", artist_song_path(@artist, song), method: :delete, data: {confirm: "You sure?"}, id: "deletesong"%></h6>
  </ul>

  <%end%>
  <%end%>

  </div>



  <%= render 'songs/form' %>

  <%= link_to 'Back', artists_path %>

  <a href="#" id="deleteallsongs">[Delete all songs]</a>
  <a><%= link_to "[Delete artist]", artist_path(@artist), method: :delete, data: {confirm: "You sure?"}, id: "deleteartist" %></a>


<style>
img {
    display: inline-block;
    border: 1px solid #ddd;
    border-radius: 4px;
    padding: 5px;
    width: 300px;
}

img:hover {
    box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodaisseurifyII</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Add jQuery -->
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist, @artist.songs.new] do |f| %>

<div>
  <form>
    <input type="text" id="new-song" placeholder="here comes the song">
  </form> </br>

</div>
<%end%>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', artist_path()@artist) %>